<a href="https://colab.research.google.com/github/Basit2002/Machine-Learning/blob/main/Copy_of_phising_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%pip install ucimlrepo

## Importing the dataset

In [ ]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
phishing_websites = fetch_ucirepo(id=327)

# data (as pandas dataframes)
X = phishing_websites.data.features
y = phishing_websites.data.targets

# metadata
#print(X.head)

# variable information
#print(y.tail)


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
print(X_train)

In [ ]:
print(y_train)

In [ ]:
print(X_test)

In [ ]:
print(y_test)

## Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
y_pred_array = y_pred.reshape(-1, 1)

# Convert y_test DataFrame to a NumPy array
y_test_array = y_test.to_numpy().reshape(-1, 1)

# Concatenate the arrays along the second axis
result = np.concatenate((y_pred_array, y_test_array), axis=1)

# Print the result
print(result)

[[-1 -1]
 [-1 -1]
 [ 1 -1]
 ...
 [-1  1]
 [-1  1]
 [ 1  1]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 905  109]
 [  75 1122]]


0.9167797376752601

**KNN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 1, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

In [ ]:
y_pred = classifier.predict(X_test)
y_pred_array = y_pred.reshape(-1, 1)

# Convert y_test DataFrame to a NumPy array
y_test_array = y_test.to_numpy().reshape(-1, 1)

# Concatenate the arrays along the second axis
result = np.concatenate((y_pred_array, y_test_array), axis=1)

# Print the result
print(result)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 959   55]
 [  27 1170]]


0.9629127091813658

## **KERNEL SVM**

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

In [ ]:
y_pred = classifier.predict(X_test)
y_pred_array = y_pred.reshape(-1, 1)

# Convert y_test DataFrame to a NumPy array
y_test_array = y_test.to_numpy().reshape(-1, 1)

# Concatenate the arrays along the second axis
result = np.concatenate((y_pred_array, y_test_array), axis=1)

# Print the result
print(result)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 933   81]
 [  50 1147]]


0.9407507914970602

## **RANDOM FOREST**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 50, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

<ipython-input-103-ef233365df31>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier.fit(X_train, y_train)


RandomForestClassifier(criterion='entropy', n_estimators=50, random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
y_pred_array = y_pred.reshape(-1, 1)

# Convert y_test DataFrame to a NumPy array
y_test_array = y_test.to_numpy().reshape(-1, 1)

# Concatenate the arrays along the second axis
result = np.concatenate((y_pred_array, y_test_array), axis=1)

# Print the result
print(result)

[[-1 -1]
 [-1 -1]
 [ 1 -1]
 ...
 [ 1  1]
 [ 1  1]
 [ 1  1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 965   49]
 [  12 1185]]


0.9724106739032112

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed whe

Accuracy: 97.15 %
Standard Deviation: 0.64 %


## **SUPPORT VECTOR**

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

In [ ]:
y_pred = classifier.predict(X_test)
y_pred_array = y_pred.reshape(-1, 1)

# Convert y_test DataFrame to a NumPy array
y_test_array = y_test.to_numpy().reshape(-1, 1)

# Concatenate the arrays along the second axis
result = np.concatenate((y_pred_array, y_test_array), axis=1)

# Print the result
print(result)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 904  110]
 [  71 1126]]


0.9181365897783809

## **NAIVE BAYES**

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

In [ ]:
y_pred = classifier.predict(X_test)
y_pred_array = y_pred.reshape(-1, 1)

# Convert y_test DataFrame to a NumPy array
y_test_array = y_test.to_numpy().reshape(-1, 1)

# Concatenate the arrays along the second axis
result = np.concatenate((y_pred_array, y_test_array), axis=1)

# Print the result
print(result)

[[-1 -1]
 [-1 -1]
 [-1 -1]
 ...
 [-1  1]
 [-1  1]
 [ 1  1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1014    0]
 [ 851  346]]


0.6151062867480778

## **DECISION TREE**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

In [ ]:
y_pred = classifier.predict(X_test)
y_pred_array = y_pred.reshape(-1, 1)

# Convert y_test DataFrame to a NumPy array
y_test_array = y_test.to_numpy().reshape(-1, 1)

# Concatenate the arrays along the second axis
result = np.concatenate((y_pred_array, y_test_array), axis=1)

# Print the result
print(result)

[[-1 -1]
 [-1 -1]
 [ 1 -1]
 ...
 [ 1  1]
 [ 1  1]
 [ 1  1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 961   53]
 [  23 1174]]


0.9656264133876075

## **XGBOOST**

In [ ]:
import numpy as np
from xgboost import XGBClassifier

# Assuming y_train is your target variable
y_train_adjusted = (y_train + 1) / 2

classifier = XGBClassifier()
classifier.fit(X_train, y_train_adjusted)


In [ ]:
import numpy as np

# Assuming y_test is a NumPy array
y_test_array = y_test.to_numpy().reshape(-1, 1)

# Replace all occurrences of -1 with 0
y_test_array[y_test_array == -1] = 0

# Continue with the rest of your code
y_pred = classifier.predict(X_test)
y_pred_array = y_pred.reshape(-1, 1)

# Concatenate the arrays along the second axis
result = np.concatenate((y_pred_array, y_test_array), axis=1)

# Print the result
print(result)


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 968   46]
 [  23 1174]]


0.9687924016282226

## Visualising the Training set results

## Visualising the Test set results